version: '3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - db-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=festa
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 81:80
    networks:
      - db-network
    environment:
      - PMA_ARBITRARY=1

networks:
  db-network: